[package]
name = "rust_tokenizer"
version = "0.1.0"
authors = ["Keith <keith@keithalcock.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/rust_tokenizer.rs"

[dependencies]
jni = "0.19.0"
tokenizers = "0.11.3"
