name: Scala-Transformers CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
        #distribution: temurin
        #java-version: 11
    - name: Run tests
      run: sbt test
